chore(ci): Fix concurrent upload issue (#3452)
Fix for a build error:
```
Total file: 1 ---- Processed file: 0 (0%)
Fail to upload '/Users/runner/work/1/a/esy-cache.tar' due to 'Blob is incomplete (missing block). Blob: 2b3f8daca8a3eb1185aa281878e01ace, Expected Offset: 0, Actual Offset: 4194304'.
Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: 2b3f8daca8a3eb1185aa281878e01ace, Expected Offset: 0, Actual Offset: 4194304
 ---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: 2b3f8daca8a3eb1185aa281878e01ace, Expected Offset: 0, Actual Offset: 4194304
   --- End of inner exception stack trace ---
```
https://dev.azure.com/onivim/oni2/_build/results?buildId=16435&view=logs&j=83eba23a-9ede-5c86-668a-3657d4d2e8d1&t=caeb8a87-5847-54ed-1bb9-47821a9bb3ac&l=950

Seems like a similar issue to https://github.com/microsoft/azure-pipelines-tasks/issues/12102#issuecomment-676736884 - which was due to a concurrent build upload (both MacOS strategies for Onivim - the hygiene check and mac build - were both trying to push up the cache artifact). For `master` builds, this disables the hygiene check strategy, which will remove the concurrent artifact upload.